/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConceptAuroraRouteImport } from './routes/concept-aurora'
import { Route as ConceptBoardRouteImport } from './routes/concept-board'
import { Route as ConceptCompactRouteImport } from './routes/concept-compact'
import { Route as ConceptSplitRouteImport } from './routes/concept-split'
import { Route as ConceptStylesRouteImport } from './routes/concept-styles'
import { Route as ConceptsRouteImport } from './routes/concepts'
import { Route as DesignRouteImport } from './routes/design'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptAuroraRoute = ConceptAuroraRouteImport.update({
  id: '/concept-aurora',
  path: '/concept-aurora',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptBoardRoute = ConceptBoardRouteImport.update({
  id: '/concept-board',
  path: '/concept-board',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptCompactRoute = ConceptCompactRouteImport.update({
  id: '/concept-compact',
  path: '/concept-compact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptSplitRoute = ConceptSplitRouteImport.update({
  id: '/concept-split',
  path: '/concept-split',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptStylesRoute = ConceptStylesRouteImport.update({
  id: '/concept-styles',
  path: '/concept-styles',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsRoute = ConceptsRouteImport.update({
  id: '/concepts',
  path: '/concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/concept-aurora': typeof ConceptAuroraRoute
  '/concept-board': typeof ConceptBoardRoute
  '/concept-compact': typeof ConceptCompactRoute
  '/concept-split': typeof ConceptSplitRoute
  '/concept-styles': typeof ConceptStylesRoute
  '/concepts': typeof ConceptsRoute
  '/design': typeof DesignRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/concept-aurora': typeof ConceptAuroraRoute
  '/concept-board': typeof ConceptBoardRoute
  '/concept-compact': typeof ConceptCompactRoute
  '/concept-split': typeof ConceptSplitRoute
  '/concept-styles': typeof ConceptStylesRoute
  '/concepts': typeof ConceptsRoute
  '/design': typeof DesignRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/concept-aurora': typeof ConceptAuroraRoute
  '/concept-board': typeof ConceptBoardRoute
  '/concept-compact': typeof ConceptCompactRoute
  '/concept-split': typeof ConceptSplitRoute
  '/concept-styles': typeof ConceptStylesRoute
  '/concepts': typeof ConceptsRoute
  '/design': typeof DesignRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/concept-aurora'
    | '/concept-board'
    | '/concept-compact'
    | '/concept-split'
    | '/concept-styles'
    | '/concepts'
    | '/design'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/concept-aurora'
    | '/concept-board'
    | '/concept-compact'
    | '/concept-split'
    | '/concept-styles'
    | '/concepts'
    | '/design'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/concept-aurora'
    | '/concept-board'
    | '/concept-compact'
    | '/concept-split'
    | '/concept-styles'
    | '/concepts'
    | '/design'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConceptAuroraRoute: typeof ConceptAuroraRoute
  ConceptBoardRoute: typeof ConceptBoardRoute
  ConceptCompactRoute: typeof ConceptCompactRoute
  ConceptSplitRoute: typeof ConceptSplitRoute
  ConceptStylesRoute: typeof ConceptStylesRoute
  ConceptsRoute: typeof ConceptsRoute
  DesignRoute: typeof DesignRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept-aurora': {
      id: '/concept-aurora'
      path: '/concept-aurora'
      fullPath: '/concept-aurora'
      preLoaderRoute: typeof ConceptAuroraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept-board': {
      id: '/concept-board'
      path: '/concept-board'
      fullPath: '/concept-board'
      preLoaderRoute: typeof ConceptBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept-compact': {
      id: '/concept-compact'
      path: '/concept-compact'
      fullPath: '/concept-compact'
      preLoaderRoute: typeof ConceptCompactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept-split': {
      id: '/concept-split'
      path: '/concept-split'
      fullPath: '/concept-split'
      preLoaderRoute: typeof ConceptSplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept-styles': {
      id: '/concept-styles'
      path: '/concept-styles'
      fullPath: '/concept-styles'
      preLoaderRoute: typeof ConceptStylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts': {
      id: '/concepts'
      path: '/concepts'
      fullPath: '/concepts'
      preLoaderRoute: typeof ConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConceptAuroraRoute: ConceptAuroraRoute,
  ConceptBoardRoute: ConceptBoardRoute,
  ConceptCompactRoute: ConceptCompactRoute,
  ConceptSplitRoute: ConceptSplitRoute,
  ConceptStylesRoute: ConceptStylesRoute,
  ConceptsRoute: ConceptsRoute,
  DesignRoute: DesignRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
