// The API's view of the shared domain. Re-exported from @pace/validation so the
// rest of apps/api imports "the domain" from one local place — and so the shared
// contract is proven to resolve across the workspace. The tRPC procedures validate
// their inputs against these.
export {
  type ActivityAction,
  type ActivityMeta,
  activityActionSchema,
  activityMetaSchema,
  type NewStatus,
  type NewStatusGroup,
  type NewTag,
  type NewTask,
  type NewTaskActivity,
  newStatusGroupSchema,
  newStatusSchema,
  newTagSchema,
  newTaskActivitySchema,
  newTaskSchema,
  type Regen,
  regenSchema,
  reorderSchema,
  type SetParent,
  type SetRecurrence,
  type Status,
  type StatusCategory,
  type StatusGroup,
  setParentSchema,
  setRecurrenceSchema,
  statusCategorySchema,
  statusGroupSchema,
  statusIdSchema,
  statusSchema,
  type Tag,
  type Task,
  type TaskActivity,
  type TaskActivityQuery,
  type TaskTag,
  tagIdSchema,
  tagSchema,
  taskActivityQuerySchema,
  taskActivitySchema,
  taskIdSchema,
  taskSchema,
  taskTagSchema,
  type UpdateStatus,
  type UpdateStatusGroup,
  type UpdateTag,
  type UpdateTask,
  type UpdateUserSettings,
  type UserSettings,
  updateStatusGroupSchema,
  updateStatusSchema,
  updateTagSchema,
  updateTaskSchema,
  updateUserSettingsSchema,
  userSettingsSchema,
} from "@pace/validation"
